---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: ambassador-admin
    port: 8877
    targetPort: 8877
  selector:
    service: ambassador
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: {{ .Release.Namespace }}  
spec:
  type: {{ .Values.oneai.portType }}
  ports:
   - port: 80
     name: http
   - port: 443
     name: https
  selector:
    service: ambassador
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: ambassador
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccounts.oneai.name }}
      {{ if .Values.oneai.secureRegistry -}}
      imagePullSecrets:
      - name: regcred-{{ .Release.Name }}
      {{- end }}
      containers:
      - name: ambassador
        image: {{ .Values.oneai.releaseRepository }}/uidp-ambassador:{{ .Values.oneai.releaseTag }}
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      - name: statsd
        image: {{ .Values.oneai.releaseRepository }}/uidp-statsd:{{ .Values.oneai.releaseTag }}
      restartPolicy: Always
