---
apiVersion: v1
kind: Service
metadata:
  name: datasource-service
  namespace: {{ .Release.Namespace }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  datasource-mapping
      prefix: /dts/api/v1/
      rewrite: /api/v1/
      service: datasource-service:8101
      cors:
        origins: "*"
        headers: Content-Type, Authorization, Accept
spec:
  selector:
    app: uidp
    component: uidp-cp-datasource-service
  ports:
  - protocol: TCP
    name: datasource-service
    port: 8103
    targetPort: 8103
---
# Use case service deployment
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: uidp-cp-datasource-service
  namespace: {{ .Release.Namespace }}
  labels:
    component: uidp-cp-datasource-service
    app: uidp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: uidp-cp-datasource-service
      app: uidp
  template:
    metadata:
      name: uidp-cp-datasource-service
      labels:
        component: uidp-cp-datasource-service
        app: uidp
    spec:
      containers:
      - name: uidp-cp-datasource-service
        image: {{ .Values.oneai.releaseRepository }}/uidp-cp-datasource-service:{{ .Values.oneai.releaseTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8103
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: uidp-postgres-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: uidp-postgres-credentials
                key: password
          - name: POSTGRES_HOST
            value: uidp-postgres

      {{ if .Values.oneai.secureRegistry -}}
      imagePullSecrets:
      - name: regcred-{{ .Release.Name }}
      {{- end }}
---
