{{ if .Values.oneai.secureRegistry -}}
---
# Docker Registry Credentials
apiVersion: v1
kind: Secret
metadata:
  name:  regcred-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: uidp
    name: regcred-{{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.oneai.registryKey }}
---
