---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: &Labels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: seldon-core-operator
    app: seldon-cluster-manager-server    
    chart: {{ template "seldon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: seldon-core
  name: {{ .Release.Name }}-seldon-cluster-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
{{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.serviceAccounts.seldon.name }}
{{- end }}
      containers:
      - env:
        - name: JAVA_OPTS
          value: {{ .Values.seldon.cluster_manager.java_opts }}
        - name: SPRING_OPTS
          value: {{ .Values.seldon.cluster_manager.spring_opts }}
        - name: SELDON_CLUSTER_MANAGER_REDIS_HOST
          value: {{ .Release.Name }}-redis
        - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
          value: {{ .Values.seldon.engine.image.name }}
        - name: ENGINE_CONTAINER_IMAGE_PULL_POLICY
          value: {{ .Values.seldon.engine.image.pull_policy }}
        - name: ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME
          value: {{ .Values.seldon.engine.service_account.name }}
        - name: SELDON_CLUSTER_MANAGER_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.seldon.cluster_manager.image.name }}
        imagePullPolicy: {{ .Values.seldon.cluster_manager.image.pull_policy }}
        name: seldon-cluster-manager-container
        securityContext:
          runAsUser: 8888
        ports:
        - containerPort: 8080
          protocol: TCP
      terminationGracePeriodSeconds: 1
