---
apiVersion: v1
kind: Service
metadata:
  name: usecase-service
  namespace: {{ .Release.Namespace }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  usecase-mapping
      prefix: /uc/api/v1/
      rewrite: /api/v1/
      service: usecase-service:8101
      cors:
        origins: "*"
        headers: Content-Type, Authorization, Accept
spec:
  selector:
    app: uidp
    component: uidp-cp-usecase-service
  ports:
  - protocol: TCP
    name: usecase-service
    port: 8101
    targetPort: 8101
---
# Use case service deployment
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: uidp-cp-usecase-service
  namespace: {{ .Release.Namespace }}
  labels:
    component: uidp-cp-usecase-service
    app: uidp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: uidp-cp-usecase-service
      app: uidp
  template:
    metadata:
      name: uidp-cp-usecase-service
      labels:
        component: uidp-cp-usecase-service
        app: uidp
    spec:
      containers:
      - name: uidp-cp-usecase-service
        image: {{ .Values.oneai.releaseRepository }}/uidp-cp-usecase-service:{{ .Values.oneai.releaseTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8101
      {{ if .Values.oneai.secureRegistry -}}
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: uidp-postgres-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uidp-postgres-credentials
      imagePullSecrets:
      - name: regcred-{{ .Release.Name }}
      {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "uidp-usecase-init"
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "uidp-usecase-init"
      labels:
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: usecase-post-install-job
        image: {{ .Values.oneai.releaseRepository }}/uidp-cp-usecase-service:{{ .Values.oneai.releaseTag }}
        imagePullPolicy: Always
        command: ["/app/init.sh"]
