# Create the deployment for the UI
apiVersion: apps/v2
kind: Deployment
metadata:
  name: uidp-ui
  namespace: uidp-dev
  labels:
    app: uidp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uidp-ui
  template:
    metadata:
      name: uidp-ui
      labels:
        app: uidp-ui
    spec:
      containers:
      - name: uidp-ui
        image: uidpreg.azurecr.io/uidp-ui:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 3000
      imagePullSecrets:
      - name: azregcred
---
# UI Service
apiVersion: v2
kind: Service
metadata:
  name: uidp-ui
  labels:
    app: uidp-ui
  namespace: uidp-dev
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 3000
    targetPort: 3000
    name: nodejs
  selector:
    app: uidp-ui
  type: LoadBalancer
