# Generate the namespace
apiVersion: v1
kind: Namespace
metadata:
  name: "uidp-dev"
  labels:
    name: "uidp-dev"
---
# Generate secrets for Keycloak certificates
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: uidp-dev
  labels:
    app: keycloak
    layer: auth
data:
  admin_password: "bGV0bWVpbjEyMw=="

---
# Create a config map for Keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
  namespace: uidp-dev
  labels:
    app: keycloak
    layer: auth
data:
  admin_user: "uidp"
---
# Deployment for keycloak
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
    layer: auth
    project: uidp-dev
  namespace: uidp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      layer: auth
  template:
    metadata:
      name: keycloak
      labels:
        name: keycloak
        app: keycloak
        layer: auth
    spec:
      containers:
        - image: jboss/keycloak:latest
          name: keycloak
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: admin_user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: admin_password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: H2
          ports:
            - containerPort: 8080
              name: http
---
# Keycloak Service
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    layer: auth
  namespace: uidp-dev
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak
    layer: auth
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

